version: '3.8'

services:
  mosquitto:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1883:1883"  # MQTT port
      - "8883:8883" # Mosquitto DB
      - "1000:1000"  # Dynsec API port
      - "1001:1001"  # Monitor API port (HTTPS)
      - "1002:1002"  # MQTT Monitor API port
      - "1003:1003"  # AWS Bridge API port
      - "8080:8080"  # Other apps port
      - "2000:2000"  # Frontend port
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./backend/mosquitto/config/mosquitto.conf:/etc/mosquitto/mosquitto.conf:ro
      #- ./backend/mosquitto/dynsec/dynamic-security.json:/var/lib/mosquitto/dynamic-security.json
      #- ./backend/mosquitto/db/:/var/lib/mosquitto/
      #- ./backend/mosquitto/dynsec:/var/lib/mosquitto
      - ./backend/app:/app
      - ./backend/logs:/var/log/mosquitto
      - ./backend/logs/api:/var/log/api  # API activity logs
      #- mosquitto_data:/var/lib/mosquitto
      #- ./data:/var/lib/mosquitto
      - ./ssl_certificates:/app/certs  # SSL certificates
      - ./backend/etc/mosquitto/certs:/etc/mosquitto/certs
      - ./backend/etc/mosquitto/conf.d:/etc/mosquitto/conf.d
      - ./frontend:/frontend  # Mount frontend source code
    environment:
      # MQTT Settings
      - MQTT_BROKER=localhost
      - MQTT_PORT=1883
      - MQTT_USERNAME=bunker
      - MQTT_PASSWORD=bunker
      # Security Settings
      - JWT_SECRET=${JWT_SECRET:-default_jwt_secret_replace_in_production}
      - API_KEY=jNnSqXybFymzgrpKTWdEjZcHvkeNBtwQY7zYyibeemfBCPU5uWIa7wIxpX4dazcP1yJ52DVFDenvcmnRqX4yaz9TVnaiqoZuDf5ILi7FGsyStvW4TwexMSW2UrUpuEoZ
      - VITE_API_KEY=NnSqXybFymzgrpKTWdEjZcHvkeNBtwQY7zYyibeemfBCPU5uWIa7wIxpX4dazcP1yJ52DVFDenvcmnRqX4yaz9TVnaiqoZuDf5ILi7FGsyStvW4TwexMSW2UrUpuEoZ
      - FRONTEND_URL=https://localhost:2000
      - ALLOWED_ORIGINS=https://localhost:2000
      - ALLOWED_HOSTS=localhost,127.0.0.1
      # Rate Limiting
      - RATE_LIMIT_PER_MINUTE=100
      # SSL Configuration
      - SSL_CERT_PATH=/app/certs/cert.pem
      - SSL_KEY_PATH=/app/certs/key.pem
      # Logging
      - LOG_LEVEL=INFO
      - API_LOG_FILE=/var/log/api/api_activity.log
      - VITE_AWS_BRIDGE_API_URL=https://localhost:2000/api/aws-bridge
    restart: unless-stopped
    networks:
      - bunker-mqtt
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost:1001/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3


networks:
  bunker-mqtt:
    external: true

volumes:
  mosquitto_data:
    driver: local
